# suppress inspection "UnusedProperty" for whole file
server.port=8889

management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true

spring.jackson.deserialization.fail-on-missing-creator-properties=true
spring.jackson.deserialization.fail-on-null-for-primitives=true

# Core web package: dispatching, handler mappings, and argument resolution
logging.level.org.springframework.web=DEBUG
# Fine-grained tracing inside the RequestMappingHandlerAdapter, where method arguments are resolved
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE
# Show exceptions that occur before controller exception handlers (like type mismatches, missing parameters, etc.)
logging.level.org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver=DEBUG
# Show exceptions in validation and data binding logic
logging.level.org.springframework.validation=DEBUG

spring.datasource.url=jdbc:h2:file:../quizdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Compare @Entiti classes with DB schema. Add DB tables and columns if needed. Does not remove anything
spring.jpa.hibernate.ddl-auto=update
# See generated SQL statements in console
spring.jpa.show-sql=true

spring.h2.console.enabled=true
# Disable H2's tracing/diagnostic output in the console to reduce noise and avoid exposing internal trace details
spring.h2.console.settings.trace=false
# Block accessing my DB from other machines on the local network
spring.h2.console.settings.web-allow-others=false
