# suppress inspection "UnusedProperty" for whole file

# Reduce logs
logging.level.org.springframework.web=WARN
logging.level.org.springframework.web.servlet.mvc.method.annotation=WARN
logging.level.org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver=WARN
logging.level.org.springframework.validation=WARN

# Set in-memory DB
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

# Drop DB after each test
spring.jpa.hibernate.ddl-auto=create-drop
# Hide SQL statements in console
spring.jpa.show-sql=false

# Disable H2 console
spring.h2.console.enabled=false